name: Linux Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential pkg-config \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev

      - name: Create output dir
        run: mkdir -p bin

      - name: Compile
        run: |
          g++ src/IgcViewer.cpp -o bin/IgcViewer \
          $(pkg-config --cflags --libs gtk+-3.0 webkit2gtk-4.1) \
          -static-libgcc -static-libstdc++

      - name: Verify output
        run: ls -R bin

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: IgcViewer-linux
          path: bin/IgcViewer
